// Vialtry — Automotive Accessories Vertical Attributes (North America)
import { AttributeDef, stripHtml } from '../pdp'

export const automotiveAttributes: AttributeDef[] = [
  { category:'Automotive', attribute:'vehicle_compatibility', label:'Vehicle Compatibility', ai_weight:10, required:'Required',
    auto_fix:'Add vehicle compatibility: year range, make, model. "Fits 2015-2024 Toyota Camry".',
    check:(p)=>/fits|compatible|for \d{4}|year|make|model|universal fit|all vehicles/i.test(stripHtml(p.body_html)) },
  { category:'Automotive', attribute:'installation_type', label:'Installation Type', ai_weight:10, required:'Required',
    auto_fix:'Add installation type: plug-and-play, hardwire, adhesive, clamp mount.',
    check:(p)=>/plug.and.play|hardwire|adhesive|clamp|mount|install|no drill|tool.free/i.test(stripHtml(p.body_html)) },
  { category:'Automotive', attribute:'material_durability', label:'Material & Durability', ai_weight:9, required:'Required',
    auto_fix:'Add material specs: ABS plastic, stainless steel, aluminum, UV-resistant, weatherproof.',
    check:(p)=>/abs|stainless|aluminum|uv.resistant|weatherproof|durable|heavy.duty/i.test(stripHtml(p.body_html)) },
  { category:'Automotive', attribute:'certifications', label:'Safety Certifications (DOT/SAE)', ai_weight:10, required:'Required',
    auto_fix:'Add certifications: DOT approved, SAE certified, FMVSS compliant.',
    check:(p)=>/dot|sae|fmvss|certified|approved|compliant/i.test(stripHtml(p.body_html)) },
  { category:'Automotive', attribute:'dimensions_fit', label:'Dimensions & Fitment', ai_weight:9, required:'Required',
    auto_fix:'Add exact dimensions: "Fits seats up to 58 wide", "12V socket compatible".',
    check:(p)=>/dimension|\d+.*x.*\d+|fits up to|compatible with|\d+ inch/i.test(stripHtml(p.body_html)) },
  { category:'Automotive', attribute:'warranty', label:'Warranty', ai_weight:9, required:'Required',
    auto_fix:'Add warranty: "Lifetime warranty", "2-year manufacturer warranty".',
    check:(p)=>/warranty|guarantee|lifetime|\d+ year/i.test(stripHtml(p.body_html)) },
  { category:'Automotive', attribute:'weather_resistance', label:'Weather / Temperature Resistance', ai_weight:9, required:'Recommended',
    auto_fix:'Add weather resistance: "Operates in -40F to 185F", "IP67 waterproof rated".',
    check:(p)=>/waterproof|water.resistant|ip\d\d|temperature|heat.resistant|weatherproof/i.test(stripHtml(p.body_html))||true },
  { category:'Automotive', attribute:'whats_included', label:'What\'s Included', ai_weight:9, required:'Required',
    auto_fix:'List everything included: main unit, mounting hardware, cables, manual.',
    check:(p)=>/include|package|comes with|in the box|what.*included/i.test(stripHtml(p.body_html)) },
  { category:'Automotive', attribute:'use_case', label:'Use Case / Problem Solved', ai_weight:10, required:'Required',
    auto_fix:'Add use case: "Eliminates blind spots", "Keeps car interior organized".',
    check:(p)=>/eliminates|reduces|improves|solves|designed for|perfect for|ideal for/i.test(stripHtml(p.body_html)) },
  { category:'Automotive', attribute:'installation_time', label:'Installation Time', ai_weight:8, required:'Recommended',
    auto_fix:'Add installation time: "Installs in under 10 minutes", "No professional installation needed".',
    check:(p)=>/install in|\d+ minute|quick install|easy install|no professional/i.test(stripHtml(p.body_html))||true },
]
