// Vialtry — Baby & Kids Vertical Attributes (North America)
import { AttributeDef, stripHtml } from '../pdp'

export const babyAttributes: AttributeDef[] = [
  { category:'Baby', attribute:'age_range', label:'Age Range', ai_weight:10, required:'Required',
    auto_fix:'Add specific age range: "0-3 months", "2-5 years". Critical for AI parent queries.',
    check:(p)=>/month|year|\d+m\b|\d+y\b|newborn|infant|toddler|preschool|kids|teen/i.test(p.tags?.toLowerCase()||stripHtml(p.body_html).toLowerCase()) },
  { category:'Baby', attribute:'safety_certification', label:'Safety Certification (ASTM/CPSC)', ai_weight:10, required:'Required',
    auto_fix:'Add US safety certifications: ASTM F963, CPSC compliant, BPA-free, JPMA certified.',
    check:(p)=>/astm|cpsc|bpa.free|phthalate|lead.free|fda|cpsia|certified|safety/i.test(stripHtml(p.body_html)) },
  { category:'Baby', attribute:'choking_hazard', label:'Choking Hazard Warning', ai_weight:10, required:'Required',
    auto_fix:'Add choking hazard warning: "Not for children under 3 years. Small parts."',
    check:(p)=>{ const isSmall=/toy|game|puzzle|bead/i.test(p.product_type||p.tags||''); if(!isSmall)return true; return /choking hazard|not for children under|small parts/i.test(stripHtml(p.body_html)) } },
  { category:'Baby', attribute:'material_safety', label:'Material Safety (BPA/Phthalate Free)', ai_weight:10, required:'Required',
    auto_fix:'Add material safety: BPA-free, phthalate-free, non-toxic, food-grade silicone.',
    check:(p)=>/bpa.free|phthalate.free|non.toxic|food.grade|natural|organic|safe for babies/i.test(stripHtml(p.body_html)) },
  { category:'Baby', attribute:'developmental_benefit', label:'Developmental Benefit', ai_weight:9, required:'Required',
    auto_fix:'Add developmental benefits: "Develops fine motor skills", "Encourages sensory exploration".',
    check:(p)=>/motor skill|sensory|cognitive|language|developmental benefit|learning/i.test(stripHtml(p.body_html)) },
  { category:'Baby', attribute:'washing_instructions', label:'Washing / Cleaning Instructions', ai_weight:9, required:'Required',
    auto_fix:'Add cleaning: machine washable, hand wash, wipe clean, dishwasher safe.',
    check:(p)=>/machine wash|hand wash|wipe clean|dishwasher|clean with|sanitize/i.test(stripHtml(p.body_html)) },
  { category:'Baby', attribute:'assembly_supervision', label:'Adult Supervision Required', ai_weight:9, required:'Required',
    auto_fix:'State supervision: "Adult assembly required" or "Adult supervision recommended".',
    check:(p)=>/adult supervision|parental supervision|adult assembly|supervision required/i.test(stripHtml(p.body_html))||true },
  { category:'Baby', attribute:'size_dimensions', label:'Product Dimensions / Weight', ai_weight:9, required:'Required',
    auto_fix:'Add product dimensions and weight for furniture, gear, and equipment.',
    check:(p)=>/\d+.*x.*\d+|dimension|weight|size|cm|inch|lbs|kg/i.test(stripHtml(p.body_html)) },
  { category:'Baby', attribute:'compatibility', label:'Compatibility (Stroller/Car Seat)', ai_weight:9, required:'Recommended',
    auto_fix:'Add compatibility: "Fits most standard strollers", "Compatible with Graco car seats".',
    check:(p)=>{ const needsCompat=/stroller|car seat|carrier|crib|bassinet/i.test(p.product_type||p.tags||''); if(!needsCompat)return true; return /compatible|fits|works with|universal/i.test(stripHtml(p.body_html)) } },
  { category:'Baby', attribute:'eco_friendly', label:'Eco-Friendly / Sustainable', ai_weight:8, required:'Recommended',
    auto_fix:'Add eco claims: organic cotton, recycled materials, sustainable sourcing.',
    check:(p)=>/organic|recycled|sustainable|eco.friendly|natural|non.toxic/i.test(stripHtml(p.body_html))||true },
]
