// Vialtry — Electronics & Gadgets Vertical Attributes (North America)
import { AttributeDef, stripHtml } from '../pdp'

export const electronicsAttributes: AttributeDef[] = [
  { category:'Electronics', attribute:'technical_specs', label:'Technical Specifications', ai_weight:10, required:'Required',
    auto_fix:'Add key specs: processor, RAM, storage, display, battery for devices.',
    check:(p)=>/processor|cpu|ram|storage|display|battery|resolution|ghz|gb|tb/i.test(stripHtml(p.body_html)) },
  { category:'Electronics', attribute:'connectivity', label:'Connectivity Options', ai_weight:10, required:'Required',
    auto_fix:'Add connectivity: WiFi standard, Bluetooth version, USB ports, HDMI, 5G/4G.',
    check:(p)=>/wifi|bluetooth|usb|hdmi|5g|4g|lte|wireless|ethernet|thunderbolt/i.test(stripHtml(p.body_html)) },
  { category:'Electronics', attribute:'compatibility', label:'Device Compatibility', ai_weight:10, required:'Required',
    auto_fix:'Add compatibility: iOS/Android, Windows/Mac, specific device models.',
    check:(p)=>/ios|android|windows|mac|compatible with|works with|iphone|samsung/i.test(stripHtml(p.body_html)) },
  { category:'Electronics', attribute:'battery_life', label:'Battery Life / Capacity', ai_weight:10, required:'Required',
    auto_fix:'Add battery life in hours and mAh: "Up to 12 hours, 5000mAh".',
    check:(p)=>{ const hasBattery=/wireless|bluetooth|portable|laptop|phone|earbuds|speaker/i.test(p.product_type||p.tags||''); if(!hasBattery)return true; return /battery|mah|hours|standby|charge time/i.test(stripHtml(p.body_html)) } },
  { category:'Electronics', attribute:'warranty_support', label:'Warranty & Support', ai_weight:10, required:'Required',
    auto_fix:'Add warranty: "1-year manufacturer warranty", "2-year extended warranty available".',
    check:(p)=>/warranty|guarantee|\d+ year|\d+ month|support/i.test(stripHtml(p.body_html)) },
  { category:'Electronics', attribute:'certifications', label:'Safety Certifications (FCC/CE/UL)', ai_weight:10, required:'Required',
    auto_fix:'Add US certifications: FCC certified, UL listed, Energy Star, RoHS compliant.',
    check:(p)=>/fcc|ul listed|energy star|rohs|ce certified|certified/i.test(stripHtml(p.body_html)) },
  { category:'Electronics', attribute:'whats_in_box', label:'What\'s in the Box', ai_weight:9, required:'Required',
    auto_fix:'Add box contents: device, cables, adapters, manuals included.',
    check:(p)=>/in the box|what.*include|package content|comes with|box include/i.test(stripHtml(p.body_html)) },
  { category:'Electronics', attribute:'dimensions_weight', label:'Dimensions & Weight', ai_weight:9, required:'Required',
    auto_fix:'Add dimensions (L x W x H) in inches and weight in lbs/oz.',
    check:(p)=>/\d+.*x.*\d+|dimension|weight|\d+ lbs|\d+ oz|\d+mm/i.test(stripHtml(p.body_html)) },
  { category:'Electronics', attribute:'use_cases', label:'Use Cases / Who It\'s For', ai_weight:10, required:'Required',
    auto_fix:'Add use cases: "Perfect for gaming, streaming, and remote work".',
    check:(p)=>/perfect for|ideal for|designed for|great for|best for/i.test(stripHtml(p.body_html)) },
  { category:'Electronics', attribute:'smart_features', label:'Smart / AI Features', ai_weight:9, required:'Recommended',
    auto_fix:'Add smart features: voice control, app control, AI-powered, Alexa/Google compatible.',
    check:(p)=>/alexa|google assistant|siri|voice control|app control|smart|ai.powered/i.test(stripHtml(p.body_html))||true },
  { category:'Electronics', attribute:'setup_ease', label:'Setup / Installation Ease', ai_weight:8, required:'Recommended',
    auto_fix:'Add setup info: "Plug and play", "5-minute setup", "No app required".',
    check:(p)=>/plug and play|easy setup|quick setup|no app|\d+ minute setup/i.test(stripHtml(p.body_html))||true },
]
