// Vialtry — Health & Wellness Vertical Attributes (North America)
import { AttributeDef, stripHtml } from '../pdp'

export const healthAttributes: AttributeDef[] = [
  { category:'Health', attribute:'supplement_form', label:'Supplement Form', ai_weight:10, required:'Required',
    auto_fix:'Add supplement form: capsule, tablet, powder, gummy, liquid, softgel, spray.',
    check:(p)=>{ const isSupplement=/supplement|vitamin|protein|probiotic|collagen|omega/i.test(p.product_type||p.tags||''); if(!isSupplement)return true; return /capsule|tablet|powder|gummy|liquid|softgel|spray/i.test(stripHtml(p.body_html)) } },
  { category:'Health', attribute:'active_ingredients', label:'Active Ingredients & Dosage', ai_weight:10, required:'Required',
    auto_fix:'List all active ingredients with mg/mcg dosage per serving. Required for US supplement labeling.',
    check:(p)=>{ const isSupplement=/supplement|vitamin|protein|probiotic/i.test(p.product_type||p.tags||''); if(!isSupplement)return true; return /mg|mcg|iu|ingredient|active|per serving/i.test(stripHtml(p.body_html)) } },
  { category:'Health', attribute:'health_benefit', label:'Health Benefits / Claims', ai_weight:10, required:'Required',
    auto_fix:'Add specific health benefits: "Supports immune system", "Promotes joint health".',
    check:(p)=>/support|promote|improve|boost|enhance|help|benefit/i.test(stripHtml(p.body_html)) },
  { category:'Health', attribute:'serving_size', label:'Serving Size & Directions', ai_weight:10, required:'Required',
    auto_fix:'Add serving size and directions: "Take 2 capsules daily with food".',
    check:(p)=>{ const isSupplement=/supplement|vitamin|protein/i.test(p.product_type||p.tags||''); if(!isSupplement)return true; return /serving size|take \d|directions|how to use|per day/i.test(stripHtml(p.body_html)) } },
  { category:'Health', attribute:'fda_disclaimer', label:'FDA Disclaimer', ai_weight:10, required:'Required',
    auto_fix:'Add FDA disclaimer: "These statements have not been evaluated by the FDA."',
    check:(p)=>{ const isSupplement=/supplement|vitamin|protein|probiotic/i.test(p.product_type||p.tags||''); if(!isSupplement)return true; return /fda|not been evaluated|diagnose|treat|cure|prevent/i.test(stripHtml(p.body_html)) } },
  { category:'Health', attribute:'certifications', label:'Third-Party Certifications', ai_weight:10, required:'Required',
    auto_fix:'Add certifications: NSF, USP, Informed Sport, GMP certified, USDA Organic, Non-GMO.',
    check:(p)=>/nsf|usp|informed sport|gmp|usda organic|non.gmo|third.party|certified|lab tested/i.test(stripHtml(p.body_html)) },
  { category:'Health', attribute:'allergen_info', label:'Allergen Information', ai_weight:10, required:'Required',
    auto_fix:'Add allergen info: gluten-free, dairy-free, soy-free, nut-free, vegan.',
    check:(p)=>/gluten.free|dairy.free|soy.free|nut.free|vegan|vegetarian|allergen|contains no/i.test(stripHtml(p.body_html)) },
  { category:'Health', attribute:'who_its_for', label:'Who It\'s For', ai_weight:10, required:'Required',
    auto_fix:'Add target customer: "For adults 18+", "For active women", "For athletes over 40".',
    check:(p)=>/for adults|for women|for men|for athletes|for seniors|for ages|designed for/i.test(stripHtml(p.body_html)) },
  { category:'Health', attribute:'contraindications', label:'Contraindications / Warnings', ai_weight:9, required:'Required',
    auto_fix:'Add warnings: "Consult physician if pregnant", "Keep out of reach of children".',
    check:(p)=>/consult|physician|doctor|pregnant|nursing|warning|keep out of reach/i.test(stripHtml(p.body_html)) },
  { category:'Health', attribute:'storage_instructions', label:'Storage Instructions', ai_weight:8, required:'Required',
    auto_fix:'Add storage: "Store in cool, dry place", "Refrigerate after opening".',
    check:(p)=>/store|storage|keep|refrigerate|cool|dry place|room temperature/i.test(stripHtml(p.body_html)) },
  { category:'Health', attribute:'results_timeline', label:'Expected Results Timeline', ai_weight:9, required:'Recommended',
    auto_fix:'Add results timeline: "See results in 4-6 weeks", "Feel the difference in 30 days".',
    check:(p)=>/results in|feel the|see the|within \d|after \d|\d+ days|\d+ weeks/i.test(stripHtml(p.body_html))||true },
]
