// Vialtry — Pet Care Vertical Attributes (North America)
import { AttributeDef, stripHtml } from '../pdp'

export const petAttributes: AttributeDef[] = [
  { category:'Pet', attribute:'pet_type', label:'Pet Type', ai_weight:10, required:'Required',
    auto_fix:'Add pet type tag: dogs, cats, birds, fish, small animals, reptiles.',
    check:(p)=>/dog|cat|bird|fish|rabbit|hamster|guinea pig|reptile|pet/i.test(p.tags?.toLowerCase()||stripHtml(p.body_html).toLowerCase()) },
  { category:'Pet', attribute:'breed_size', label:'Breed Size / Pet Size', ai_weight:10, required:'Required',
    auto_fix:'Add pet size: small, medium, large, extra-large, all sizes, toy breeds.',
    check:(p)=>/small breed|medium breed|large breed|toy breed|giant|all size|small dog|large dog/i.test(p.tags?.toLowerCase()||stripHtml(p.body_html).toLowerCase()) },
  { category:'Pet', attribute:'age_suitability', label:'Age Suitability', ai_weight:10, required:'Required',
    auto_fix:'Add age: puppy/kitten (0-1yr), adult (1-7yr), senior (7yr+).',
    check:(p)=>/puppy|kitten|adult|senior|all ages|young|mature/i.test(p.tags?.toLowerCase()||stripHtml(p.body_html).toLowerCase()) },
  { category:'Pet', attribute:'ingredients', label:'Ingredients / Formula', ai_weight:10, required:'Required',
    auto_fix:'Add full ingredient list for food/treats. List first 5 ingredients prominently.',
    check:(p)=>{ const isFood=/food|treat|supplement|chew|snack/i.test(p.product_type||p.tags||''); if(!isFood)return true; return /ingredient|formula|contains|made with/i.test(stripHtml(p.body_html)) } },
  { category:'Pet', attribute:'nutritional_info', label:'Nutritional Information', ai_weight:9, required:'Required',
    auto_fix:'Add nutritional analysis: protein %, fat %, fiber %, moisture % for pet food.',
    check:(p)=>{ const isFood=/food|treat/i.test(p.product_type||p.tags||''); if(!isFood)return true; return /protein|fat|fiber|moisture|calorie|kcal/i.test(stripHtml(p.body_html)) } },
  { category:'Pet', attribute:'safety_certifications', label:'Safety / Quality Certifications', ai_weight:10, required:'Required',
    auto_fix:'Add: AAFCO compliant, FDA approved, USDA organic, veterinarian recommended.',
    check:(p)=>/aafco|fda|usda|vet.recommend|veterinarian|certified|approved/i.test(stripHtml(p.body_html)) },
  { category:'Pet', attribute:'material_safety', label:'Material Safety (Non-Toxic)', ai_weight:10, required:'Required',
    auto_fix:'Add: non-toxic, BPA-free, food-grade materials for toys and accessories.',
    check:(p)=>{ const isAccessory=/toy|bed|collar|leash|bowl|feeder/i.test(p.product_type||p.tags||''); if(!isAccessory)return true; return /non.toxic|bpa.free|food.grade|safe|natural material/i.test(stripHtml(p.body_html)) } },
  { category:'Pet', attribute:'feeding_guidelines', label:'Feeding Guidelines', ai_weight:9, required:'Required',
    auto_fix:'Add feeding guidelines: serving size by pet weight, daily frequency.',
    check:(p)=>{ const isFood=/food|treat|supplement/i.test(p.product_type||p.tags||''); if(!isFood)return true; return /feeding guide|serving size|daily|per day|cup|tablespoon/i.test(stripHtml(p.body_html)) } },
  { category:'Pet', attribute:'health_benefits', label:'Health Benefits', ai_weight:9, required:'Required',
    auto_fix:'Add health benefits: joint support, coat health, digestive health, dental health.',
    check:(p)=>/joint|coat|digestive|dental|immune|heart|brain|energy|weight management/i.test(stripHtml(p.body_html)) },
  { category:'Pet', attribute:'country_of_origin', label:'Country of Origin', ai_weight:8, required:'Required',
    auto_fix:'Add country of origin. US-made is a strong trust signal for pet food.',
    check:(p)=>/made in|country of origin|manufactured in|sourced from/i.test(stripHtml(p.body_html)) },
  { category:'Pet', attribute:'allergen_free', label:'Allergen Free / Grain Free', ai_weight:8, required:'Recommended',
    auto_fix:'Add allergen info: grain-free, gluten-free, hypoallergenic, limited ingredient.',
    check:(p)=>/grain.free|gluten.free|allergen|hypoallergenic|limited ingredient|novel protein/i.test(stripHtml(p.body_html))||true },
]
