// Vialtry — Sports & Fitness Vertical Attributes (North America)
import { AttributeDef, stripHtml } from '../pdp'

export const sportsAttributes: AttributeDef[] = [
  { category:'Sports', attribute:'sport_type', label:'Sport / Activity Type', ai_weight:10, required:'Required',
    auto_fix:'Add sport type tag: running, yoga, gym, cycling, swimming, hiking, tennis, basketball etc.',
    check:(p)=>/running|yoga|gym|cycling|swimming|hiking|tennis|basketball|football|cricket|golf|climbing|crossfit/i.test(p.tags?.toLowerCase()||stripHtml(p.body_html).toLowerCase()) },
  { category:'Sports', attribute:'fitness_level', label:'Fitness Level', ai_weight:9, required:'Required',
    auto_fix:'Add fitness level: beginner, intermediate, advanced, professional.',
    check:(p)=>/beginner|intermediate|advanced|professional|amateur|elite/i.test(p.tags?.toLowerCase()||stripHtml(p.body_html).toLowerCase()) },
  { category:'Sports', attribute:'performance_features', label:'Performance Features', ai_weight:10, required:'Required',
    auto_fix:'Add 3-5 performance features: anti-slip, shock absorption, moisture-wicking, UV protection etc.',
    check:(p)=>/anti.slip|shock|moisture.wick|breathable|uv protection|quick.dry|anti.odor|compression|grip/i.test(stripHtml(p.body_html)) },
  { category:'Sports', attribute:'material_quality', label:'Material / Build Quality', ai_weight:9, required:'Required',
    auto_fix:'Add material details: steel gauge, rubber grade, fabric composition for durability signals.',
    check:(p)=>/steel|rubber|foam|nylon|polyester|aluminum|carbon|neoprene|spandex|mesh/i.test(stripHtml(p.body_html)) },
  { category:'Sports', attribute:'weight_capacity', label:'Weight / Load Capacity', ai_weight:10, required:'Required',
    auto_fix:'Add max weight/load capacity in lbs and kg for equipment.',
    check:(p)=>{ const isEquip=/equipment|machine|rack|bench|dumbbell|barbell|kettlebell|treadmill/i.test(p.product_type||p.tags||''); if(!isEquip)return true; return /lbs|kg|capacity|max weight|load/i.test(stripHtml(p.body_html)) } },
  { category:'Sports', attribute:'warranty', label:'Product Warranty', ai_weight:9, required:'Required',
    auto_fix:'Add warranty: frame warranty, parts warranty, labor warranty duration.',
    check:(p)=>/warranty|guarantee|\d+ year|\d+ month/i.test(stripHtml(p.body_html)) },
  { category:'Sports', attribute:'indoor_outdoor', label:'Indoor / Outdoor Use', ai_weight:9, required:'Required',
    auto_fix:'Add usage environment: indoor only or suitable for outdoor use.',
    check:(p)=>/indoor|outdoor|inside|outside|all.weather|weatherproof/i.test(p.tags?.toLowerCase()||stripHtml(p.body_html).toLowerCase()) },
  { category:'Sports', attribute:'who_its_for', label:'Who It\'s For', ai_weight:10, required:'Required',
    auto_fix:'Add target user: "Ideal for beginners building home gym" or "For competitive cyclists".',
    check:(p)=>/ideal for|designed for|perfect for|for beginners|for athletes|for professionals/i.test(stripHtml(p.body_html)) },
  { category:'Sports', attribute:'certification', label:'Safety Certification', ai_weight:9, required:'Recommended',
    auto_fix:'Add safety certifications: ASTM, CE, ISO, CPSC compliance for equipment.',
    check:(p)=>/astm|ce certified|iso|cpsc|certified|safety standard/i.test(stripHtml(p.body_html))||true },
  { category:'Sports', attribute:'assembly_required', label:'Assembly Required', ai_weight:8, required:'Required',
    auto_fix:'State clearly: "Assembly required" or "Ready to use". Include assembly time estimate.',
    check:(p)=>/assembly|assemble|no assembly|ready to use|pre.assembled/i.test(stripHtml(p.body_html))||true },
]
