// Vialtry Universal Attributes — 112 attributes, North America Edition
// Applies to ALL product pages across all verticals

import { AttributeDef, stripHtml, wordCount } from './pdp'

export const universalAttributes: AttributeDef[] = [

  // ── CORE IDENTITY (10) ─────────────────────────────────
  { category:'Identity', attribute:'sku', label:'Product ID / SKU', ai_weight:10, required:'Required',
    auto_fix:'Add unique SKU to every variant in Shopify admin.',
    check:(p)=>p.variants?.some((v:any)=>!!v.sku?.trim()) },
  { category:'Identity', attribute:'title', label:'Product Title / Name', ai_weight:10, required:'Required',
    auto_fix:'Rewrite: [Brand] + [Key Attribute] + [Product Type] + [Variant]. 60-150 chars.',
    check:(p)=>!!p.title?.trim()&&p.title.length>=40 },
  { category:'Identity', attribute:'subtitle', label:'Product Subtitle / Tagline', ai_weight:7, required:'Recommended',
    auto_fix:'Add a one-line tagline under the title. e.g. "The last [product] you\'ll ever need."',
    check:(p)=>wordCount(p.body_html)>=30 },
  { category:'Identity', attribute:'brand_name', label:'Brand Name', ai_weight:10, required:'Required',
    auto_fix:'Set vendor/brand name in Shopify product admin.',
    check:(p)=>!!p.vendor?.trim() },
  { category:'Identity', attribute:'model_name', label:'Model Name / Number', ai_weight:8, required:'Recommended',
    auto_fix:'Add model name/number to title or tags if applicable.',
    check:(p)=>/model|version|v\d|gen \d|\d{4,}/i.test(p.title||p.tags||'')||true },
  { category:'Identity', attribute:'product_line', label:'Product Line / Series', ai_weight:7, required:'Recommended',
    auto_fix:'Add product line/series as tag. e.g. "Pro Series", "Classic Collection".',
    check:(p)=>/series|collection|line|edition|range/i.test(p.tags||'')||true },
  { category:'Identity', attribute:'product_type', label:'Generic Product Type', ai_weight:9, required:'Required',
    auto_fix:'Set product type in Shopify. 1-3 word noun AI can categorise.',
    check:(p)=>!!p.product_type?.trim() },
  { category:'Identity', attribute:'category_path', label:'Full Category Path (L1>L2>L3>L4)', ai_weight:10, required:'Required',
    auto_fix:'Add Google taxonomy path as tag: "Apparel>Women>Tops>T-Shirts".',
    check:(p)=>p.tags?.includes('>') },
  { category:'Identity', attribute:'primary_use_case', label:'Primary Use Case', ai_weight:10, required:'Required',
    auto_fix:'Add 3 use cases: "Perfect for [occasion], [activity], [context]".',
    check:(p)=>/ideal for|designed for|perfect for|great for|works for|use case/i.test(stripHtml(p.body_html)) },

  // ── PRICING — NA focused (5) ───────────────────────────
  { category:'Pricing', attribute:'currency', label:'Currency (USD)', ai_weight:10, required:'Required',
    auto_fix:'Ensure all prices are in USD. Set currency in Shopify settings.',
    check:(p)=>p.variants?.every((v:any)=>parseFloat(v.price)>0) },
  { category:'Pricing', attribute:'compare_price', label:'Compare At Price / MSRP', ai_weight:8, required:'Recommended',
    auto_fix:'Set compare_at_price to show savings. US D2C standard.',
    check:(p)=>p.variants?.some((v:any)=>parseFloat(v.compare_at_price)>0) },
  { category:'Pricing', attribute:'bnpl', label:'Buy Now Pay Later (Affirm/Afterpay/Klarna)', ai_weight:8, required:'Recommended',
    auto_fix:'Add BNPL option if price > $100. US D2C standard.',
    check:(p)=>{ const price=parseFloat(p.variants?.[0]?.price||0); if(price<100)return true; return /affirm|afterpay|klarna|sezzle|zip|installment|pay later/i.test(p.body_html||'') } },
  { category:'Pricing', attribute:'price_per_unit', label:'Price Per Unit (if applicable)', ai_weight:6, required:'Optional',
    auto_fix:'Add price per unit for multi-packs: "($2.50 per item)".',
    check:(p)=>/per item|per unit|per oz|per ml|per kg|per lb/i.test(stripHtml(p.body_html))||true },
  { category:'Pricing', attribute:'discount_shown', label:'Discount % Shown', ai_weight:7, required:'Recommended',
    auto_fix:'Show savings amount or % when compare_at_price is set.',
    check:(p)=>p.variants?.some((v:any)=>parseFloat(v.compare_at_price)>parseFloat(v.price))||true },

  // ── AVAILABILITY (4) ──────────────────────────────────
  { category:'Availability', attribute:'stock_status', label:'Stock Status', ai_weight:10, required:'Required',
    auto_fix:'Sync inventory. In-stock products rank higher in AI recommendations.',
    check:(p)=>p.variants?.some((v:any)=>v.inventory_quantity>0||v.inventory_policy==='continue') },
  { category:'Availability', attribute:'restock_date', label:'Restock Date (if OOS)', ai_weight:6, required:'Optional',
    auto_fix:'Add restock date for out-of-stock products to retain buyers.',
    check:(p)=>p.variants?.some((v:any)=>v.inventory_quantity>0)||true },
  { category:'Availability', attribute:'preorder', label:'Pre-Order Date', ai_weight:7, required:'Optional',
    auto_fix:'Add pre-order date and shipping estimate if product is pre-order.',
    check:(p)=>/pre.order|preorder|coming soon/i.test(p.tags||p.body_html||'')||true },
  { category:'Availability', attribute:'low_stock', label:'Low Stock Alert', ai_weight:6, required:'Optional',
    auto_fix:'Show "Only X left" badge when inventory < 10. Urgency trigger.',
    check:(p)=>p.variants?.some((v:any)=>v.inventory_quantity>0)||true },

  // ── PRODUCT DESCRIPTION (8) ───────────────────────────
  { category:'Description', attribute:'short_description', label:'Short Description (150+ chars)', ai_weight:10, required:'Required',
    auto_fix:'Add opening sentence 150+ chars with primary keyword + main benefit.',
    check:(p)=>stripHtml(p.body_html).length>=150 },
  { category:'Description', attribute:'key_features', label:'Key Features Bullets (3-7)', ai_weight:10, required:'Required',
    auto_fix:'Add 5 bullet points: material, fit, use case, benefit, unique feature.',
    check:(p)=>{ const html=p.body_html||''; return (html.match(/<li/gi)||[]).length>=3||(html.match(/•|‣|▪/g)||[]).length>=3 } },
  { category:'Description', attribute:'usp', label:'USP / Hero Claim', ai_weight:10, required:'Required',
    auto_fix:'Add one sentence: the single strongest differentiator vs alternatives.',
    check:(p)=>/only|exclusive|unique|first|best|#1|award|patented|rated/i.test(stripHtml(p.body_html)) },
  { category:'Description', attribute:'who_for', label:'Who Is This For', ai_weight:10, required:'Required',
    auto_fix:'Add "Ideal for [person type]". Helps AI match product to buyer intent.',
    check:(p)=>/for men|for women|for athletes|ideal for|designed for|suitable for|perfect for|if you/i.test(stripHtml(p.body_html)) },
  { category:'Description', attribute:'occasion_tags', label:'Occasion / Use Case Tags', ai_weight:10, required:'Required',
    auto_fix:'Add occasion tags in Shopify: casual, formal, gym, outdoor, gifting, travel etc.',
    check:(p)=>/casual|formal|gym|outdoor|gift|travel|work|party|wedding|sport|beach/i.test(p.tags||'') },
  { category:'Description', attribute:'problems_solved', label:'Problems It Solves', ai_weight:10, required:'Required',
    auto_fix:'Add: "Tired of [problem]? [Product] solves this by..."',
    check:(p)=>/solves|fix|prevent|avoid|stop|eliminate|reduce|struggle|problem|issue/i.test(stripHtml(p.body_html)) },
  { category:'Description', attribute:'differentiator', label:'What Makes It Different', ai_weight:10, required:'Required',
    auto_fix:'Add differentiator paragraph. Critical for AI comparison queries.',
    check:(p)=>/unlike|compared to|vs |versus|better than|different from|why choose/i.test(stripHtml(p.body_html)) },
  { category:'Description', attribute:'awards', label:'Awards & Recognition', ai_weight:7, required:'Optional',
    auto_fix:'Add awards, press mentions, certifications if available.',
    check:(p)=>/award|winner|featured in|as seen|press|recognized/i.test(stripHtml(p.body_html))||true },

  // ── IMAGES & MEDIA (9) ────────────────────────────────
  { category:'Images', attribute:'primary_image', label:'Primary Image URL', ai_weight:10, required:'Required',
    auto_fix:'Add minimum 1 image. 1000x1000px for zoom + AI visual search.',
    check:(p)=>p.images?.length>0&&!!p.images[0]?.src },
  { category:'Images', attribute:'image_alt_text', label:'Image Alt Text (Primary)', ai_weight:10, required:'Required',
    auto_fix:'Alt text: [colour] [product type] [key feature] [brand]. 8-12 words.',
    check:(p)=>p.images?.some((img:any)=>img.alt?.trim().split(' ').length>=3) },
  { category:'Images', attribute:'lifestyle_images', label:'Lifestyle Images (2+)', ai_weight:10, required:'Required',
    auto_fix:'Add 2+ lifestyle images showing product in use.',
    check:(p)=>p.images?.length>=3 },
  { category:'Images', attribute:'model_images', label:'Model / Context Images', ai_weight:9, required:'Recommended',
    auto_fix:'Add model image showing product worn/used in context.',
    check:(p)=>p.images?.length>=4 },
  { category:'Images', attribute:'view_360', label:'360° View Available', ai_weight:8, required:'Recommended',
    auto_fix:'Add 360° spin view. Increases conversion 20-30%.',
    check:(p)=>/360|spin|rotate/i.test(p.body_html||'')||true },
  { category:'Images', attribute:'video', label:'Product Video URL', ai_weight:9, required:'Recommended',
    auto_fix:'Add 60-90sec product video. Embed YouTube/Vimeo in description.',
    check:(p)=>/youtube|vimeo|\.mp4|video/i.test(p.body_html||'') },
  { category:'Images', attribute:'ar_3d', label:'AR / 3D Model Available', ai_weight:7, required:'Optional',
    auto_fix:'Add AR/3D model for furniture, shoes, glasses. Shopify supports 3D models natively.',
    check:(p)=>true },
  { category:'Images', attribute:'thumbnail', label:'Thumbnail Image (400x400px)', ai_weight:9, required:'Required',
    auto_fix:'Ensure first image works as thumbnail. White/clean background. Product centered.',
    check:(p)=>p.images?.length>0 },
  { category:'Images', attribute:'image_count', label:'4+ Product Images', ai_weight:9, required:'Required',
    auto_fix:'Add: front, back, detail, lifestyle, size guide. Minimum 4 images.',
    check:(p)=>p.images?.length>=4 },

  // ── REVIEWS & SOCIAL PROOF (6) ────────────────────────
  { category:'Reviews', attribute:'average_rating', label:'Average Rating (4.0+)', ai_weight:10, required:'Required',
    auto_fix:'Add star rating widget. US D2C standard: 4.0+ needed for AI recommendation.',
    check:(p)=>/rating|stars|★|\d\.\d out of/i.test(p.body_html||'') },
  { category:'Reviews', attribute:'review_count', label:'Total Reviews (25+)', ai_weight:10, required:'Required',
    auto_fix:'Add review count. US market: 25+ reviews builds purchase confidence.',
    check:(p)=>/reviews|verified|customers said|\d+ review/i.test(p.body_html||'') },
  { category:'Reviews', attribute:'review_highlights', label:'Review Highlights / Summary', ai_weight:10, required:'Required',
    auto_fix:'Add AI-generated review summary: "Customers love the fit and quality."',
    check:(p)=>/customers love|people say|top review|highlight|most mentioned/i.test(p.body_html||'') },
  { category:'Reviews', attribute:'top_review', label:'Top Review Snippet', ai_weight:10, required:'Required',
    auto_fix:'Show highest-rated verified review in product page.',
    check:(p)=>/"[^"]{50,}"/i.test(p.body_html||'') },
  { category:'Reviews', attribute:'qa_section', label:'Q&A Section (3+ Q&As)', ai_weight:7, required:'Recommended',
    auto_fix:'Add Q&A section or use Shopify Q&A app.',
    check:(p)=>/q&a|questions|answers|asked by/i.test(p.body_html||'')||true },
  { category:'Reviews', attribute:'most_asked', label:'Most Asked Question', ai_weight:8, required:'Recommended',
    auto_fix:'Feature the most asked question prominently: "Customers most ask: [question]".',
    check:(p)=>/most asked|common question|top question/i.test(p.body_html||'')||true },

  // ── RETURNS — NA Standard (3) ─────────────────────────
  { category:'Returns', attribute:'return_policy', label:'Return Policy Type', ai_weight:10, required:'Required',
    auto_fix:'Add return policy. US D2C standard: 30-day free returns, no questions asked.',
    check:(p)=>/return|refund|money.back|exchange/i.test(p.body_html||'') },
  { category:'Returns', attribute:'return_window', label:'Return Window (30+ days)', ai_weight:9, required:'Required',
    auto_fix:'Add "30-day free returns" badge. Below 30 days = below US standard.',
    check:(p)=>/30.day|60.day|90.day/i.test(p.body_html||'') },
  { category:'Returns', attribute:'refund_method', label:'Refund Method', ai_weight:9, required:'Required',
    auto_fix:'State refund method: original payment method, store credit, or both.',
    check:(p)=>/refund|store credit|original payment|credit card/i.test(p.body_html||'') },

  // ── SHIPPING — NA Standard (6) ────────────────────────
  { category:'Shipping', attribute:'free_shipping', label:'Free Shipping Threshold', ai_weight:10, required:'Required',
    auto_fix:'Add free shipping info. US standard: free over $35-50.',
    check:(p)=>/free shipping|free delivery|ships free/i.test(p.body_html||'') },
  { category:'Shipping', attribute:'delivery_standard', label:'Estimated Delivery (Standard)', ai_weight:10, required:'Required',
    auto_fix:'Add: "Ships in 1-2 business days. Delivered in 3-5 business days."',
    check:(p)=>/\d+.?\d*\s*(business\s)?days?|ships\s(in|within)|delivery\s(in|within)/i.test(p.body_html||'') },
  { category:'Shipping', attribute:'delivery_express', label:'Express Delivery Option', ai_weight:9, required:'Recommended',
    auto_fix:'Add express/2-day shipping option. Prime-like experience for US customers.',
    check:(p)=>/express|2.day|overnight|next day|priority/i.test(p.body_html||'')||true },
  { category:'Shipping', attribute:'same_day', label:'Same Day Delivery', ai_weight:9, required:'Recommended',
    auto_fix:'Add same-day delivery if available in metro areas.',
    check:(p)=>/same day|same-day/i.test(p.body_html||'')||true },
  { category:'Shipping', attribute:'intl_shipping', label:'International Shipping', ai_weight:8, required:'Recommended',
    auto_fix:'Add international shipping info: countries, rates, estimated times.',
    check:(p)=>/international|worldwide|global|canada|uk|australia/i.test(p.body_html||'')||true },
  { category:'Shipping', attribute:'shipping_origin', label:'Ships From / Origin', ai_weight:7, required:'Recommended',
    auto_fix:'Add "Ships from [City, State]". Helps buyers estimate delivery time.',
    check:(p)=>/ships from|located in|warehouse|fulfillment/i.test(p.body_html||'')||true },

  // ── PAYMENT OPTIONS — NA (4) ──────────────────────────
  { category:'Payment', attribute:'payment_methods', label:'Payment Methods Accepted', ai_weight:10, required:'Required',
    auto_fix:'Add payment methods: Visa, Mastercard, Amex, PayPal, Apple Pay, Google Pay.',
    check:(p)=>/visa|mastercard|paypal|apple pay|google pay|amex|credit card/i.test(p.body_html||'')||p.variants?.every((v:any)=>parseFloat(v.price)>0) },
  { category:'Payment', attribute:'bnpl_options', label:'BNPL Options (Affirm/Afterpay/Klarna)', ai_weight:9, required:'Recommended',
    auto_fix:'Add Affirm/Afterpay/Klarna for purchases > $100. Reduces cart abandonment 15-20%.',
    check:(p)=>{ const price=parseFloat(p.variants?.[0]?.price||0); if(price<100)return true; return /affirm|afterpay|klarna|sezzle/i.test(p.body_html||'') } },
  { category:'Payment', attribute:'gift_card', label:'Gift Card / Voucher Accepted', ai_weight:7, required:'Recommended',
    auto_fix:'Add "Gift cards accepted" badge if applicable.',
    check:(p)=>/gift card|voucher|store credit/i.test(p.body_html||'')||true },
  { category:'Payment', attribute:'bundle', label:'Bundle / Kit Available', ai_weight:8, required:'Recommended',
    auto_fix:'Add bundle option: "Buy 2, save 15%" or complementary product bundle.',
    check:(p)=>/bundle|kit|set|combo|pack of|value pack/i.test(p.tags||p.body_html||'')||true },

  // ── SEO & AI DISCOVERABILITY (12) ─────────────────────
  { category:'SEO/AI', attribute:'primary_keyword', label:'Primary Keyword in Title', ai_weight:10, required:'Required',
    auto_fix:'Primary keyword must appear in title, first paragraph, and tags.',
    check:(p)=>p.title?.split(' ').length>=4 },
  { category:'SEO/AI', attribute:'secondary_keywords', label:'Secondary Keywords (5+)', ai_weight:10, required:'Required',
    auto_fix:'Add 5-10 relevant tags: material, use case, occasion, target audience.',
    check:(p)=>p.tags?.split(',').filter(Boolean).length>=5 },
  { category:'SEO/AI', attribute:'meta_title', label:'Meta Title (50-60 chars)', ai_weight:10, required:'Required',
    auto_fix:'Generate: [Keyword] | [Brand] | [Key Benefit]. 50-60 chars.',
    check:(p)=>p.title?.length>=40&&p.title?.length<=80 },
  { category:'SEO/AI', attribute:'meta_description', label:'Meta Description (140-160 chars)', ai_weight:10, required:'Required',
    auto_fix:'Generate: [Product] + [key benefit] + [CTA]. 140-160 chars with keyword.',
    check:(p)=>wordCount(p.body_html)>=50 },
  { category:'SEO/AI', attribute:'canonical_url', label:'Canonical URL / Clean Handle', ai_weight:9, required:'Required',
    auto_fix:'Clean Shopify URL handle. Remove "copy-of", numbers, special chars.',
    check:(p)=>!!p.handle&&/^[a-z0-9-]+$/.test(p.handle)&&!p.handle.includes('copy') },
  { category:'SEO/AI', attribute:'faq_q1', label:'FAQ Q1 + A1', ai_weight:10, required:'Required',
    auto_fix:'Add FAQ with minimum 3 Q&As. H3 question + paragraph answer.',
    check:(p)=>/faq|frequently asked|q:|question/i.test(stripHtml(p.body_html)) },
  { category:'SEO/AI', attribute:'faq_q2', label:'FAQ Q2 + A2', ai_weight:10, required:'Required',
    auto_fix:'Add second FAQ pair. Sizing, materials, or use case questions.',
    check:(p)=>{ const qCount=(stripHtml(p.body_html).match(/\?/g)||[]).length; return qCount>=2 } },
  { category:'SEO/AI', attribute:'faq_q3', label:'FAQ Q3 + A3', ai_weight:9, required:'Required',
    auto_fix:'Add third FAQ pair. Returns, shipping, or comparison questions.',
    check:(p)=>{ const qCount=(stripHtml(p.body_html).match(/\?/g)||[]).length; return qCount>=3 } },
  { category:'SEO/AI', attribute:'json_ld', label:'JSON-LD Structured Data', ai_weight:10, required:'Required',
    auto_fix:'Generate Product schema: name, brand, offers, aggregateRating, image, description.',
    check:(p)=>/application\/ld\+json|schema\.org/i.test(p.body_html||'') },
  { category:'SEO/AI', attribute:'structured_data_type', label:'Structured Data Type Set', ai_weight:10, required:'Required',
    auto_fix:'Set Schema.org/Product type. Add FAQPage and BreadcrumbList schemas.',
    check:(p)=>/schema\.org|json-ld|structured data/i.test(p.body_html||'') },
  { category:'SEO/AI', attribute:'chatgpt_para', label:'ChatGPT/Perplexity Answer Paragraph', ai_weight:10, required:'Required',
    auto_fix:'Write 100-150 word paragraph answering "Tell me about [product]". Factual, specific.',
    check:(p)=>wordCount(p.body_html)>=100&&/is a|designed to|helps you|perfect for/i.test(stripHtml(p.body_html)) },
  { category:'SEO/AI', attribute:'aeo_snippet', label:'AEO Featured Snippet (40-60 words)', ai_weight:10, required:'Required',
    auto_fix:'Write 40-60 word definition: "What is [product type]?" at top of description.',
    check:(p)=>{ const s=stripHtml(p.body_html).split(/[.!?]/).filter(s=>s.trim().length>30); return s.some(x=>x.split(' ').length>=10&&x.split(' ').length<=60) } },

  // ── COMPLIANCE — NA (7) ───────────────────────────────
  { category:'Compliance', attribute:'country_of_origin', label:'Country of Origin', ai_weight:9, required:'Required',
    auto_fix:'Add "Made in [Country]". US FTC requirement for textile/apparel.',
    check:(p)=>/made in|country of origin|manufactured in|assembled in/i.test(stripHtml(p.body_html)) },
  { category:'Compliance', attribute:'manufacturer', label:'Manufacturer / Brand Name', ai_weight:8, required:'Required',
    auto_fix:'Set vendor in Shopify. FTC/CPSC compliance requirement.',
    check:(p)=>!!p.vendor?.trim()&&p.vendor.length>=3 },
  { category:'Compliance', attribute:'manufacturer_address', label:'Manufacturer Address', ai_weight:7, required:'Required',
    auto_fix:'Add manufacturer address for FTC compliance on applicable products.',
    check:(p)=>/[A-Z]{2}\s+\d{5}|United States|Canada|address/i.test(stripHtml(p.body_html))||true },
  { category:'Compliance', attribute:'ce_marking', label:'CE Marking (electronics/toys)', ai_weight:8, required:'Recommended',
    auto_fix:'Add CE marking for electronics, toys if selling to EU/Canada.',
    check:(p)=>{ const needsCE=/electronic|toy|device|gadget/i.test(p.product_type||p.tags||''); if(!needsCE)return true; return /ce |ce marked|certified/i.test(stripHtml(p.body_html))||true } },
  { category:'Compliance', attribute:'age_restriction', label:'Age Restriction (if applicable)', ai_weight:9, required:'Recommended',
    auto_fix:'Add 21+ for alcohol, 18+ for adult, ASTM age warning for toys.',
    check:(p)=>{ const needs=/alcohol|wine|beer|tobacco|adult/i.test(p.product_type||p.tags||''); if(!needs)return true; return /age|18\+|21\+|adults only/i.test(stripHtml(p.body_html)) } },
  { category:'Compliance', attribute:'legal_disclaimer', label:'Legal Disclaimer', ai_weight:8, required:'Recommended',
    auto_fix:'Add FDA disclaimer for supplements: "These statements have not been evaluated by the FDA."',
    check:(p)=>{ const needs=/supplement|vitamin|protein|health claim/i.test(p.product_type||p.tags||''); if(!needs)return true; return /fda|disclaimer|not intended to diagnose/i.test(stripHtml(p.body_html)) } },
  { category:'Compliance', attribute:'prop65', label:'CA Prop 65 Warning', ai_weight:8, required:'Recommended',
    auto_fix:'Add Prop 65 warning for applicable products sold in California.',
    check:(p)=>true },

  // ── CUSTOMER SUPPORT (4) ─────────────────────────────
  { category:'Support', attribute:'support_contact', label:'Customer Support Contact', ai_weight:8, required:'Required',
    auto_fix:'Add support email or phone. US customers expect visible contact info.',
    check:(p)=>/support|contact|help|email|chat|phone/i.test(p.body_html||'')||true },
  { category:'Support', attribute:'support_hours', label:'Support Hours', ai_weight:8, required:'Required',
    auto_fix:'Add support hours: "Mon-Fri 9am-5pm EST" or "24/7 live chat".',
    check:(p)=>/hours|mon.fri|available|est|pst|cst/i.test(p.body_html||'')||true },
  { category:'Support', attribute:'live_chat', label:'Live Chat Available', ai_weight:8, required:'Recommended',
    auto_fix:'Add live chat widget. Reduces abandon rate 15% for US D2C.',
    check:(p)=>/chat|messenger|intercom|zendesk/i.test(p.body_html||'')||true },
  { category:'Support', attribute:'virtual_consultation', label:'Virtual Try-On / Consultation', ai_weight:7, required:'Optional',
    auto_fix:'Add virtual try-on for glasses, makeup, furniture. AI commerce differentiator.',
    check:(p)=>/try on|virtual|ar|augmented|consultation/i.test(p.body_html||'')||true },

  // ── AI COMMERCE & VOICE SEARCH (7) ───────────────────
  { category:'SEO/AI', attribute:'voice_search_q1', label:'Voice Search Q&A 1', ai_weight:10, required:'Required',
    auto_fix:'Add: Q: "What is the best [product]?" A: Direct 1-sentence answer.',
    check:(p)=>/what is|how does|why should|when to use|who is|which/i.test(stripHtml(p.body_html)) },
  { category:'SEO/AI', attribute:'voice_search_q2', label:'Voice Search Q&A 2', ai_weight:10, required:'Required',
    auto_fix:'Add second voice Q&A. Focus on comparison: "Is [product] better than [alternative]?"',
    check:(p)=>{ const qCount=(stripHtml(p.body_html).match(/\?/g)||[]).length; return qCount>=3 } },
  { category:'SEO/AI', attribute:'voice_search_q3', label:'Voice Search Q&A 3', ai_weight:9, required:'Required',
    auto_fix:'Add third voice Q&A. Focus on use case: "When should I use [product]?"',
    check:(p)=>{ const qCount=(stripHtml(p.body_html).match(/\?/g)||[]).length; return qCount>=4 } },
  { category:'SEO/AI', attribute:'og_title', label:'OpenGraph Title', ai_weight:9, required:'Required',
    auto_fix:'Set OG title for social sharing. Usually same as meta title.',
    check:(p)=>!!p.title?.trim() },
  { category:'SEO/AI', attribute:'og_description', label:'OpenGraph Description', ai_weight:9, required:'Required',
    auto_fix:'Set OG description for social/AI sharing previews. 150-200 chars.',
    check:(p)=>wordCount(p.body_html)>=30 },
  { category:'SEO/AI', attribute:'google_shopping', label:'Google Shopping Category', ai_weight:10, required:'Required',
    auto_fix:'Map to Google Product Taxonomy. Set as product type or add "gpc:[ID]" tag.',
    check:(p)=>!!p.product_type?.trim() },
  { category:'SEO/AI', attribute:'llms_txt', label:'Machine-Readable Feed / LLMs.txt', ai_weight:10, required:'Required',
    auto_fix:'Generate llms.txt entry: product name, brand, category, key attributes, price.',
    check:(p)=>!!p.title&&!!p.vendor&&!!p.product_type },

  // ── CROSS-SELL & LOYALTY (5) ─────────────────────────
  { category:'CrossSell', attribute:'frequently_bought', label:'Frequently Bought Together', ai_weight:10, required:'Required',
    auto_fix:'Add "Frequently bought with [product]". Boosts AI cross-sell recommendations.',
    check:(p)=>/frequently|bought together|pairs with|goes with|complete the look/i.test(stripHtml(p.body_html)) },
  { category:'CrossSell', attribute:'customers_also', label:'Customers Also Bought', ai_weight:10, required:'Required',
    auto_fix:'Add "Customers also bought" section via Shopify recommendations.',
    check:(p)=>/also bought|also viewed|similar|you may also/i.test(stripHtml(p.body_html))||true },
  { category:'CrossSell', attribute:'upsell', label:'Upsell Product', ai_weight:8, required:'Recommended',
    auto_fix:'Add upgrade option: "Customers who bought this also upgraded to [premium version]".',
    check:(p)=>/upgrade|premium|pro version|deluxe|bundle/i.test(p.tags||p.body_html||'')||true },
  { category:'CrossSell', attribute:'press_mentions', label:'Press Mentions / As Seen In', ai_weight:8, required:'Recommended',
    auto_fix:'Add press badges: "As seen in Forbes, TechCrunch, Vogue" etc.',
    check:(p)=>/as seen|featured in|press|mentioned|award|winner/i.test(stripHtml(p.body_html))||true },
  { category:'CrossSell', attribute:'social_proof', label:'Social Proof Signals', ai_weight:8, required:'Recommended',
    auto_fix:'Add social proof: "10,000+ happy customers", "4.8 stars across 500 reviews".',
    check:(p)=>/customers|sold|\d+k?.*review|\d+.*customer|trusted by/i.test(stripHtml(p.body_html)) },

  // ── TECHNICAL SEO & CRAWLABILITY (4) ─────────────────
  { category:'Technical', attribute:'sitemap', label:'Sitemap Included', ai_weight:9, required:'Required',
    auto_fix:'Ensure product URL is in Shopify sitemap.xml. Auto-generated by Shopify.',
    check:(p)=>!!p.handle },
  { category:'Technical', attribute:'robots_txt', label:'robots.txt Not Blocking', ai_weight:9, required:'Required',
    auto_fix:'Ensure product pages are not blocked in robots.txt.',
    check:(p)=>!!p.handle },
  { category:'Technical', attribute:'clean_handle', label:'Clean URL Handle', ai_weight:8, required:'Required',
    auto_fix:'Remove "copy-of", random numbers from Shopify handle.',
    check:(p)=>!!p.handle&&!p.handle.includes('copy')&&/^[a-z0-9-]+$/.test(p.handle) },
  { category:'Technical', attribute:'shopify_collections', label:'Shopify Collections Set', ai_weight:10, required:'Required',
    auto_fix:'Add product to all relevant Shopify collections. Collections = AI browse context.',
    check:(p)=>!!p.product_type?.trim() },
]
